import { expect, test } from "bun:test"
import { mkdtempSync, readdirSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"

import { createAppPaths, ensureAppScaffold, runProfile, type AppRuntime } from "../src/cli.ts"
import { formatTurnResult } from "../src/shared/logger.ts"
import { initializeDatabase } from "../src/shared/session-database.ts"
import type { AgentTurnResult, ProfileId } from "../src/shared/types.ts"

import { TestModel } from "./test-model.ts"

type WalkthroughOptions = {
  profileId: ProfileId
  message: string
  userId?: string
  sessionId?: string
}

type WalkthroughStep = {
  section: string
  command: string
  options: WalkthroughOptions
  assert(result: AgentTurnResult, app: AppRuntime): Promise<void>
}

type ReportEntry = {
  section: string
  command: string
  output: string
}

const reportPath = fileURLToPath(new URL("./e2e-report.md", import.meta.url))
const RESET = "\x1b[0m"
const BOLD = "\x1b[1m"
const DIM = "\x1b[2m"
const ansi = (color: string) => Bun.color(color, "ansi") ?? ""
const PREVIEW_TITLE_COLOR = ansi("deepskyblue")
const PREVIEW_STEP_COLOR = ansi("darkorange")
const PREVIEW_RULE_COLOR = ansi("lightslategray")
const PREVIEW_COMMAND_COLOR = ansi("mediumspringgreen")
const PREVIEW_PROMPT_COLOR = ansi("gray")
const PREVIEW_META_COLOR = ansi("silver")

function makeRoot(): string {
  return mkdtempSync(join(tmpdir(), "agents-readme-e2e-"))
}

async function createTestApp(): Promise<(AppRuntime & { root: string })> {
  const root = makeRoot()
  const paths = createAppPaths(root)
  await ensureAppScaffold(paths)

  return {
    root,
    paths,
    db: initializeDatabase(paths.databasePath),
    model: new TestModel(),
  }
}

function cleanupTestApp(app: AppRuntime & { root: string }): void {
  app.db.close()
  rmSync(app.root, { recursive: true, force: true })
}

function stripAnsi(text: string): string {
  return text.replace(/\x1b\[[0-9]*m/g, "")
}

function normalizeReportText(text: string, rootDir: string): string {
  return stripAnsi(text).replaceAll(rootDir, ".")
}

function normalizePreviewText(text: string, rootDir: string): string {
  return text.replaceAll(rootDir, ".")
}

function buildCliCommand(command: string): string {
  return `bun ah ${command}`
}

function rule(text: string): string {
  return `${DIM}${PREVIEW_RULE_COLOR}${"-".repeat(text.length)}${RESET}`
}

function printPreviewHeader(total: number): void {
  const title = "README WALKTHROUGH PREVIEW"
  console.log("")
  console.log(`${BOLD}${PREVIEW_TITLE_COLOR}${title}${RESET}`)
  console.log(rule(title))
  console.log(`${DIM}${PREVIEW_META_COLOR}Steps: ${total}${RESET}`)
}

function printPreview(step: WalkthroughStep, terminalText: string, index: number, total: number, rootDir: string): void {
  const stepNumber = String(index).padStart(String(total).length, "0")
  const heading = `Step ${stepNumber}/${total}: ${step.section}`

  console.log("")
  console.log(`${BOLD}${PREVIEW_STEP_COLOR}${heading}${RESET}`)
  console.log(rule(heading))
  console.log(`${DIM}${PREVIEW_PROMPT_COLOR}$${RESET} ${PREVIEW_COMMAND_COLOR}${buildCliCommand(step.command)}${RESET}`)
  console.log("")
  console.log(normalizePreviewText(terminalText, rootDir))
}

function printPreviewFooter(): void {
  const title = "END README WALKTHROUGH PREVIEW"
  console.log("")
  console.log(`${BOLD}${PREVIEW_TITLE_COLOR}${title}${RESET}`)
  console.log(rule(title))
}

function renderReport(entries: ReportEntry[]): string {
  const parts = [
    "# E2E README Walkthrough Report",
    "",
    "Generated by `tests/e2e-readme.test.ts` using `TestModel` and `formatTurnResult()`.",
    "The terminal preview preserves ANSI styling this markdown copy strips ANSI and normalizes temp paths.",
  ]

  for (const entry of entries) {
    parts.push(
      "",
      "---",
      "",
      `## ${entry.section}`,
      "",
      "```bash",
      entry.command,
      "```",
      "",
      "```text",
      entry.output,
      "```",
    )
  }

  parts.push("")
  return parts.join("\n")
}

async function expectFileContains(path: string, text: string): Promise<void> {
  expect(await Bun.file(path).text()).toContain(text)
}

function expectToolName(result: AgentTurnResult, expected: string): void {
  expect(result.toolResults[0]?.name).toBe(expected)
}

function createWalkthroughSteps(): WalkthroughStep[] {
  return [
    {
      section: "OpenClaw Basic",
      command: '--profile openclaw --message "What shell do I prefer?"',
      options: { profileId: "openclaw", message: "What shell do I prefer?" },
      async assert(result) {
        expect(result.profileId).toBe("openclaw")
        expectToolName(result, "search_memory")
        expect(result.reply).toBe("I do not have that stored yet.")
        expect(result.debug.modelDecisions).toContain("No proactive preference in context dispatching search_memory.")
      },
    },
    {
      section: "Hermes Basic",
      command: '--profile hermes --message "What shell do I prefer?"',
      options: { profileId: "hermes", message: "What shell do I prefer?" },
      async assert(result) {
        expect(result.profileId).toBe("hermes")
        expectToolName(result, "search_memory")
        expect(result.reply).toContain("The demo project is a Bun companion implementation for the article.")
        expect(result.debug.systemPromptSections).toContain("Injected curated memory from MEMORY.md.")
      },
    },
    {
      section: "OpenClaw Explicit Memory Save",
      command: '--profile openclaw --user alice --session prefs --message "Remember that I prefer zsh for shell work"',
      options: {
        profileId: "openclaw",
        userId: "alice",
        sessionId: "prefs",
        message: "Remember that I prefer zsh for shell work",
      },
      async assert(result, app) {
        expect(result.profileId).toBe("openclaw")
        expectToolName(result, "save_memory")
        expect(result.reply).toBe("Saved explicit memory: I prefer zsh for shell work.")
        expect(result.debug.memoryWrites).toContain("Saved explicit memory: I prefer zsh for shell work")
        await expectFileContains(app.paths.memoryPath, "- I prefer zsh for shell work.")
        expect(await Bun.file(app.paths.userPath).text()).not.toContain("zsh")
      },
    },
    {
      section: "OpenClaw Explicit Memory Recall",
      command: '--profile openclaw --user alice --session prefs --message "What shell do I prefer?"',
      options: {
        profileId: "openclaw",
        userId: "alice",
        sessionId: "prefs",
        message: "What shell do I prefer?",
      },
      async assert(result) {
        expect(result.profileId).toBe("openclaw")
        expectToolName(result, "search_memory")
        expect(result.reply).toBe("Here is the strongest match I found in memory: I prefer zsh for shell work.")
      },
    },
    {
      section: "OpenClaw Log Search",
      command: '--profile openclaw --user alice --session logs --message "search recent logs for timeout failures"',
      options: {
        profileId: "openclaw",
        userId: "alice",
        sessionId: "logs",
        message: "search recent logs for timeout failures",
      },
      async assert(result) {
        expect(result.profileId).toBe("openclaw")
        expectToolName(result, "search_logs")
        expect(result.reply).toContain('I checked the demo log for "timeout failures".')
        expect(result.reply).toContain("Found 2 matching log lines.")
        expect(result.reply).toContain("demo.log:2:")
      },
    },
    {
      section: "Hermes Log Search",
      command: '--profile hermes --user alice --session logs --message "search recent logs for timeout failures"',
      options: {
        profileId: "hermes",
        userId: "alice",
        sessionId: "logs",
        message: "search recent logs for timeout failures",
      },
      async assert(result, app) {
        const reportFilePath = join(app.paths.hermesSandboxReportsDir, "timeout-failures.txt")
        const skillFiles = readdirSync(app.paths.skillsDir).filter((file) => file.endsWith(".md"))

        expect(result.profileId).toBe("hermes")
        expectToolName(result, "execute_code")
        expect(result.reply).toContain("Executed Hermes script: analyze timeout failures")
        expect(result.reply).toContain("Report: reports/timeout-failures.txt")
        expect(result.reply).toContain("Matches: 2")
        expect(result.debug.generatedSkills).toHaveLength(1)
        expect(result.debug.sandboxEvents.some((event) => event.includes("Synced Hermes sandbox fixtures into"))).toBe(true)
        expect(result.debug.sandboxEvents.some((event) => event.includes("Wrote sandbox report"))).toBe(true)
        expect(skillFiles).toHaveLength(1)
        expect(await Bun.file(reportFilePath).exists()).toBe(true)
        await expectFileContains(reportFilePath, "data/logs/demo.log:2:")
        await expectFileContains(reportFilePath, "data/logs/demo.log:3:")
      },
    },
    {
      section: "Hermes Auto-Learn Save",
      command: '--profile hermes --user alice --session prefs --message "I prefer zsh for shell work"',
      options: {
        profileId: "hermes",
        userId: "alice",
        sessionId: "prefs",
        message: "I prefer zsh for shell work",
      },
      async assert(result, app) {
        expect(result.profileId).toBe("hermes")
        expect(result.toolResults).toHaveLength(0)
        expect(result.reply).toBe('This hermes demo is using the shared agent loop. I did not need any tools for: "I prefer zsh for shell work"')
        expect(result.debug.userModelUpdates).toContain("User prefers zsh for shell work.")
        expect(result.debug.recalledEntries).toContain("session:logs:user: search recent logs for timeout failures")
        await expectFileContains(app.paths.userPath, "- User prefers zsh for shell work.")
      },
    },
    {
      section: "Hermes Auto-Learn Recall",
      command: '--profile hermes --user alice --session prefs --message "What shell do I prefer?"',
      options: {
        profileId: "hermes",
        userId: "alice",
        sessionId: "prefs",
        message: "What shell do I prefer?",
      },
      async assert(result) {
        expect(result.profileId).toBe("hermes")
        expect(result.toolResults).toHaveLength(0)
        expect(result.reply).toBe("You prefer zsh for shell work.")
        expect(result.debug.recalledEntries).toContain("session:prefs:user: I prefer zsh for shell work")
      },
    },
    {
      section: "OpenClaw Command Policy",
      command: '--profile openclaw --message "run command: grep timeout data/logs/demo.log"',
      options: { profileId: "openclaw", message: "run command: grep timeout data/logs/demo.log" },
      async assert(result) {
        expect(result.profileId).toBe("openclaw")
        expectToolName(result, "run_command")
        expect(result.toolResults[0]?.ok).toBe(false)
        expect(result.reply).toContain("Policy: needs_approval")
        expect(result.debug.permissionDecisions).toContain(
          "openclaw:grep timeout data/logs/demo.log -> needs_approval (Command is outside the OpenClaw demo allowlist.)",
        )
      },
    },
    {
      section: "Hermes Sandbox Policy",
      command: '--profile hermes --message "run command: cat /etc/hosts"',
      options: { profileId: "hermes", message: "run command: cat /etc/hosts" },
      async assert(result) {
        expect(result.profileId).toBe("hermes")
        expectToolName(result, "run_command")
        expect(result.toolResults[0]?.ok).toBe(true)
        expect(result.reply).toContain("Policy: sandboxed")
        expect(result.reply).toContain("Operation not permitted: /etc/hosts")
        expect(result.debug.permissionDecisions).toContain(
          "hermes:cat /etc/hosts -> sandboxed (Hermes runs this through the demo sandbox policy.)",
        )
      },
    },
  ]
}

test(
  "README walkthrough e2e",
  async () => {
    const app = await createTestApp()
    const steps = createWalkthroughSteps()
    const reportEntries: ReportEntry[] = []

    try {
      printPreviewHeader(steps.length)

      for (const [index, step] of steps.entries()) {
        const result = await runProfile(app, step.options)
        const terminalText = formatTurnResult(result)

        await step.assert(result, app)
        printPreview(step, terminalText, index + 1, steps.length, app.paths.rootDir)
        reportEntries.push({
          section: step.section,
          command: buildCliCommand(step.command),
          output: normalizeReportText(terminalText, app.paths.rootDir),
        })
      }

      const reportText = renderReport(reportEntries)
      await Bun.write(reportPath, reportText)
      await expectFileContains(reportPath, "# E2E README Walkthrough Report")
      await expectFileContains(reportPath, "## Hermes Log Search")
      await expectFileContains(reportPath, "Report: reports/timeout-failures.txt")
      printPreviewFooter()
      console.log(`${DIM}${PREVIEW_META_COLOR}Report written to ${reportPath}${RESET}`)
    } finally {
      cleanupTestApp(app)
    }
  },
  { timeout: 60000 },
)
