/**
 * Setup script: generates RSA key pair, writes powersync/service.yaml with
 * the public key, and creates .env with a signed development JWT.
 *
 * Run once: bun run setup
 */

const MAX_POWERSYNC_TOKEN_TTL_SECONDS = 24 * 60 * 60;
const DEFAULT_POWERSYNC_TOKEN_TTL_SECONDS = 23 * 60 * 60;

function base64url(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof ArrayBuffer ? new Uint8Array(buf) : buf;
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function getTokenTtlSeconds() {
  const raw = process.env.POWERSYNC_TOKEN_TTL_SECONDS;
  if (!raw) return DEFAULT_POWERSYNC_TOKEN_TTL_SECONDS;

  const value = Number(raw);
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error("POWERSYNC_TOKEN_TTL_SECONDS must be a positive integer.");
  }
  if (value > MAX_POWERSYNC_TOKEN_TTL_SECONDS) {
    throw new Error(
      `POWERSYNC_TOKEN_TTL_SECONDS must be ${MAX_POWERSYNC_TOKEN_TTL_SECONDS} or less.`,
    );
  }
  return value;
}

async function getExistingEnvValue(name: string) {
  const file = Bun.file(".env");
  if (!(await file.exists())) return "";

  const content = await file.text();
  const line = content
    .split(/\r?\n/)
    .find((entry) => entry.startsWith(`${name}=`));
  return line?.slice(name.length + 1) ?? "";
}

async function main() {
  // 1. Generate RSA-2048 key pair for RS256 JWTs
  const { publicKey, privateKey } = await crypto.subtle.generateKey(
    {
      name: "RSASSA-PKCS1-v1_5",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["sign", "verify"],
  );

  const pubJwk = await crypto.subtle.exportKey("jwk", publicKey);

  // 2. Sign a development JWT. PowerSync accepts a maximum 24 hour lifetime.
  const header = { alg: "RS256", typ: "JWT", kid: "powersync-dev" };
  const now = Math.floor(Date.now() / 1000);
  const tokenTtlSeconds = getTokenTtlSeconds();
  const payload = {
    sub: "agent-001",
    iss: "powersync-dev",
    aud: ["powersync-dev"],
    iat: now,
    exp: now + tokenTtlSeconds,
    user_id: "agent-001",
  };

  const headerB64 = base64url(
    new TextEncoder().encode(JSON.stringify(header)),
  );
  const payloadB64 = base64url(
    new TextEncoder().encode(JSON.stringify(payload)),
  );
  const signingInput = `${headerB64}.${payloadB64}`;

  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    privateKey,
    new TextEncoder().encode(signingInput),
  );

  const token = `${signingInput}.${base64url(signature)}`;

  // 3. Write powersync/service.yaml
  const serviceYaml = `# Auto-generated by bun run setup - do not edit manually
# Re-run: bun run setup

replication:
  connections:
    - type: postgresql
      uri: postgresql://postgres:postgres@postgres:5432/postgres
      sslmode: disable

storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_storage

port: 8080

sync_config:
  path: sync-config.yaml

client_auth:
  jwks:
    keys:
      - kty: ${pubJwk.kty}
        n: "${pubJwk.n}"
        e: "${pubJwk.e}"
        alg: RS256
        kid: powersync-dev
  audience:
    - powersync-dev
`;

  await Bun.write("powersync/service.yaml", serviceYaml);

  // 4. Write .env
  const anthropicApiKey = await getExistingEnvValue("ANTHROPIC_API_KEY");
  const envContent = `# Auto-generated by bun run setup
POWERSYNC_URL=http://localhost:8080
POWERSYNC_TOKEN=${token}
DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
# Set your LLM API key:
ANTHROPIC_API_KEY=${anthropicApiKey}
`;

  await Bun.write(".env", envContent);

  console.log("Setup complete:");
  console.log("  powersync/service.yaml — PowerSync service config with JWKS");
  console.log("  .env                   — dev token + connection URLs");
  console.log("");
  console.log("Next steps:");
  console.log("  1. Add your ANTHROPIC_API_KEY to .env");
  console.log("  2. docker compose up -d --wait");
  console.log("  3. bun run start");
}

main().catch(console.error);
